version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "conductor-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1eu69ub1do5gn"
s3_prefix = "conductor-dev"
region = "us-west-2"
profile = "devshed"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = false
parameter_overrides = "Stage=\"dev\" InstanceType=\"t3.micro\""
image_repositories = []
